name: Makers_Crew Dev CD
on:
  workflow_run:
    workflows: [ "Makers_Crew CI" ]
    branches: [ "traffic" ]
    types: [ completed ]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      working-directory-spring: main
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker build 가능하도록 환경 설정
        uses: docker/setup-buildx-action@v2

      - name: Create application.properties from secret
        run: |
          echo "${{ secrets.APPLICATION_SECRET_SPRING }}" > ./main/src/main/resources/application-secret.properties
        shell: bash

      - name: Docker hub에 로그인
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_LOGIN_ACCESSTOKEN }}

      - name: docker image 빌드 및 푸시 (Spring)
        run: |
          docker build --platform linux/amd64 -t makerscrew/main:traffic --build-arg SPRING_PROFILES_ACTIVE=traffic .
          docker push makerscrew/main:traffic
        working-directory: ${{ env.working-directory-spring }}

      - name: 도커 컨테이너 실행
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TRAFFIC_SERVER_IP }}
          username: ${{ secrets.TRAFFIC_SERVER_USER }}
          key: ${{ secrets.TRAFFIC_SERVER_KEY }}
          script: |
            cd ~
            chmod +x ./deploy.sh
            ./deploy.sh
